### ISSUE TITLE
H265 Support results in free() : invalid pointer

### ISSUE THREAD

**Issue by eslam-ahmed-khair** [WebRTSP/ReStreamer#13]
Hi there,

So I added the H265 `video/x-h265` as one the supported caps in `GstReStreamer2::prepare()` and add the proper decoding/encoding elements (`h265parse ! avdec_h265 ! x264enc tune=zerolatency` in case the stream is H265) if needed based on the cap types in `GstReStreamer2::srcPadAdded(GstElement*, GstPad*)` and whenever that stream is closed/switched via the UI, I get free() : invalid pointer

gdb stackstrace:

```
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff74b0859 in __GI_abort () at abort.c:79
#2  0x00007ffff751b3ee in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7ffff7645285 "%s\n")
    at ../sysdeps/posix/libc_fatal.c:155
#3  0x00007ffff752347c in malloc_printerr (str=str@entry=0x7ffff76434ae "free(): invalid pointer") at malloc.c:5347
#4  0x00007ffff7524cac in _int_free (av=<optimized out>, p=<optimized out>, have_lock=0) at malloc.c:4173
#5  0x00007fffa1ade801 in  () at /lib/x86_64-linux-gnu/libavcodec.so.58
#6  0x00007fffa1b10ca2 in avcodec_close () at /lib/x86_64-linux-gnu/libavcodec.so.58
#7  0x00007fffe4658f7d in  () at /usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgstlibav.so
#8  0x00007fffe4669d13 in  () at /usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgstlibav.so
#9  0x00007fffe4669e43 in  () at /usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgstlibav.so
#10 0x00007ffff6663542 in  () at /lib/x86_64-linux-gnu/libgstvideo-1.0.so.0
#11 0x00007ffff712d9f2 in gst_element_change_state () at /lib/x86_64-linux-gnu/libgstreamer-1.0.so.0
#12 0x00007ffff712e139 in  () at /lib/x86_64-linux-gnu/libgstreamer-1.0.so.0
#13 0x00007ffff710a1b8 in  () at /lib/x86_64-linux-gnu/libgstreamer-1.0.so.0
#14 0x00007ffff712d9f2 in gst_element_change_state () at /lib/x86_64-linux-gnu/libgstreamer-1.0.so.0
#15 0x00007ffff712e139 in  () at /lib/x86_64-linux-gnu/libgstreamer-1.0.so.0
#16 0x00007ffff710a1b8 in  () at /lib/x86_64-linux-gnu/libgstreamer-1.0.so.0
#17 0x00007ffff712d9f2 in gst_element_change_state () at /lib/x86_64-linux-gnu/libgstreamer-1.0.so.0
#18 0x00007ffff712daef in gst_element_change_state () at /lib/x86_64-linux-gnu/libgstreamer-1.0.so.0
#19 0x00007ffff712e139 in  () at /lib/x86_64-linux-gnu/libgstreamer-1.0.so.0
#20 0x00007ffff7ca3242 in GstStreamingSource::cleanup() (this=0x7ffff0010100)
    at /home/dev/Repos/webrtc-streaming/src/webrtc-streamer/submodules/WebRTSP/RtStreaming/GstRtStreaming/GstStreamingSource.cpp:161
```

Any clue why this might happen? I was able to produce this on 2 different machines, but it doesn't happen on my main development machine.

**Comment by RSATom** [comment]
Are you trying to use it inside some other app (i.e. not inside ReStreamer app, but with your own app)?

**Comment by eslam-ahmed-khair** [comment]
> Are you trying to use it inside some other app (i.e. not inside ReStreamer app, but with your own app)?

yes

**Comment by RSATom** [comment]
Then I bet something breaks your heap... i.e. some code overwrites memory it not own.

**Comment by RSATom** [comment]
Or it could be some threading issue - that two problems usually produces some strange issues.
Also, please check, If the error is always the same and in the same place and at the same time - if not, it's definitely something from two mentioned above issues.

**Comment by eslam-ahmed-khair** [comment]
> Or it could be some threading issue - that two problems usually produces some strange issues. Also, please check, If the error is always the same and happens in the same place and at the same time - if not, it's definitely something from two mentioned above issues.

Yes, it does happen in the same place every time. I have produced it within `ReStreamer` itself, Here's the full stacktrace:

```
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff7749859 in __GI_abort () at abort.c:79
#2  0x00007ffff77b43ee in __libc_message
    (action=action@entry=do_abort, fmt=fmt@entry=0x7ffff78de285 "%s\n")
    at ../sysdeps/posix/libc_fatal.c:155
#3  0x00007ffff77bc47c in malloc_printerr
    (str=str@entry=0x7ffff78e06e0 "corrupted size vs. prev_size while consolidating") at malloc.c:5347
#4  0x00007ffff77be1ce in _int_free
    (av=0x7fff90000020, p=0x7fff9012dfc0, have_lock=<optimized out>)
    at malloc.c:4332
#5  0x00007fff682db801 in  () at /lib/x86_64-linux-gnu/libavcodec.so.58
#6  0x00007fff6830dca2 in avcodec_close ()
    at /lib/x86_64-linux-gnu/libavcodec.so.58
#7  0x00007fffbc0f7f7d in  ()
    at /usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgstlibav.so
#8  0x00007fffbc108d13 in  ()
    at /usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgstlibav.so
#9  0x00007fffbc108e43 in  ()
    at /usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgstlibav.so
#10 0x00007ffff6f79542 in  () at /lib/x86_64-linux-gnu/libgstvideo-1.0.so.0
#11 0x00007ffff7c5f9f2 in gst_element_change_state ()
    at /lib/x86_64-linux-gnu/libgstreamer-1.0.so.0
--Type <RET> for more, q to quit, c to continue without paging--
#12 0x00007ffff7c60139 in  () at /lib/x86_64-linux-gnu/libgstreamer-1.0.so.0
#13 0x00007ffff7c3c1b8 in  () at /lib/x86_64-linux-gnu/libgstreamer-1.0.so.0
#14 0x00007ffff7c5f9f2 in gst_element_change_state () at /lib/x86_64-linux-gnu/libgstreamer-1.0.so.0
#15 0x00007ffff7c60139 in  () at /lib/x86_64-linux-gnu/libgstreamer-1.0.so.0
#16 0x00007ffff7c3c1b8 in  () at /lib/x86_64-linux-gnu/libgstreamer-1.0.so.0
#17 0x00007ffff7c5f9f2 in gst_element_change_state () at /lib/x86_64-linux-gnu/libgstreamer-1.0.so.0
#18 0x00007ffff7c5faef in gst_element_change_state () at /lib/x86_64-linux-gnu/libgstreamer-1.0.so.0
#19 0x00007ffff7c60139 in  () at /lib/x86_64-linux-gnu/libgstreamer-1.0.so.0
#20 0x000055555564edb0 in GstStreamingSource::cleanup() (this=0x5555556dc9d0)
    at /home/avidbeam/Repos/ReStreamer/WebRTSP/RtStreaming/GstRtStreaming/GstStreamingSource.cpp:190
#21 0x000055555564d799 in GstReStreamer2::cleanup() (this=0x5555556dc9d0)
    at /home/avidbeam/Repos/ReStreamer/WebRTSP/RtStreaming/GstRtStreaming/GstReStreamer2.cpp:154
#22 0x000055555564e79c in GstStreamingSource::onTeePadRemoved() (this=0x5555556dc9d0)
    at /home/avidbeam/Repos/ReStreamer/WebRTSP/RtStreaming/GstRtStreaming/GstStreamingSource.cpp:118
#23 0x000055555564e3cf in GstStreamingSource::onBusMessage(_GstMessage*) (this=0x5555556dc9d0, message=0x7fff800ce2b0)
    at /home/avidbeam/Repos/ReStreamer/WebRTSP/RtStreaming/GstRtStreaming/GstStreamingSource.cpp:63
#24 0x000055555564e537 in GstStreamingSource::<lambda(GstBus*, GstMessage*, gpointer)>::operator()(GstBus *, GstMessage *, gpointer) const
    (__closure=0x0, bus=0x7fffa4008bb0 [GstBus|bus18], message=0x7fff800ce2b0, userData=0x5555556dc9d0)
    at /home/avidbeam/Repos/ReStreamer/WebRTSP/RtStreaming/GstRtStreaming/GstStreamingSource.cpp:101
#25 0x000055555564e56a in GstStreamingSource::<lambda(GstBus*, GstMessage*, gpointer)>::_FUN(GstBus *, GstMessage *, gpointer) ()
    at /home/avidbeam/Repos/ReStreamer/WebRTSP/RtStreaming/GstRtStreaming/GstStreamingSource.cpp:102
#26 0x00007ffff7c45dc2 in  () at /lib/x86_64-linux-gnu/libgstreamer-1.0.so.0
#27 0x00007ffff7d9604e in g_main_context_dispatch () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#28 0x00007ffff7d96400 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#29 0x00007ffff7d966f3 in g_main_loop_run () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#30 0x00005555555fb431 in ReStreamerMain(http::Config const&, Config const&) (httpConfig=..., config=...)
    at /home/avidbeam/Repos/ReStreamer/ReStreamer.cpp:122
#31 0x00005555556242f0 in main(int, char**) (argc=1, argv=0x7fffffffdba8) at /home/avidbeam/Repos/ReStreamer/main.cpp:261
```

Here are the files needed to support H265:
[GstReStreamer2.cpp](https://pastebin.com/cY8PEwUG)
[GstReStreamer2.h](https://pastebin.com/NiqYeuKe)

**Comment by RSATom** [comment]
Not related to your issue, but this is wrong:

` "capssetter caps=\"application/x-rtp,profile-level-id=(string)42c015\""`

If you encode video yourself, then just encode it right to base profile-level.

**Comment by RSATom** [comment]
And since it's your private project, I'm afraid I can put it only to end of my priority queue...

**Comment by eslam-ahmed-khair** [comment]
FYI, adding support for MJPEG the same way, doesn't cause any problems.

**Comment by eslam-ahmed-khair** [comment]
I replaced `avdec_h265` with `libde265dec` and the issue is resolved. maybe it's an ffmpeg problem after all!

**Comment by RSATom** [comment]
I would recommend you try newer GStreamer version then... Just to be sure it's not fixed already.

**Comment by eslam-ahmed-khair** [comment]
Is `ReStreamer` compatible with other GStreamer versions?

**Comment by RSATom** [comment]
It should be. On weekend I've upgraded to Ubuntu 21.10 with GStreamer 1.18.5 and ReStreamer works fine for me.

**Comment by RSATom** [comment]
The minimum recommended GStreamer version is 1.17.1
