### ISSUE TITLE
Problem outside my network

### ISSUE THREAD

**Issue by more1982** [WebRTSP/ReStreamer#41]
Hello. I have a problem, when i'm using this app out of my network (in local it's working fine). So I opened port 5080, 5554 and 554 on my router, and app is working, but I can't see video, just spin. Maybe I must open some ports else? Can u help me plz?
![image](https://github.com/WebRTSP/ReStreamer/assets/63099280/508dd3ba-decb-415d-adc5-30f4db7123b2)

**Comment by RSATom** [comment]
If app is running behind NAT I'm afraid it's required to use TURN server.

**Comment by RSATom** [comment]
Other option is add forwarding for UDP port, but right now you'll have to forward almost all of them. Maybe it's possible to limit required UDP ports range - I'll check.

**Comment by RSATom** [comment]
it looks like it's possible https://gitlab.freedesktop.org/gstreamer/gst-plugins-bad/-/merge_requests/119 ...
I'll try to add support for this soon.

**Comment by more1982** [comment]
> it looks like it's possible https://gitlab.freedesktop.org/gstreamer/gst-plugins-bad/-/merge_requests/119 ... I'll try to add support for this soon.

Thank you for your fast answer. Really need this app to run on VPS out of local network.

**Comment by more1982** [comment]
> VPS? I've thought you are trying to use behind home router... What exactly cloud provider are you trying to use? Is it Amazon EC2?

This will be in future:)
Right now I'm using local network with mikrotik router. So Webrtsp server working fine inside local network. But not outside.

**Comment by RSATom** [comment]
Got it. I'll try to find solution. It's really can be useful... :+1:

**Comment by more1982** [comment]
> Got it. I'll try to find solution. It's really can be useful... 👍

I'm waitning your solution vary hard< my friend:)

**Comment by RSATom** [comment]
I just want to say with Amazon EC2 it can be simpler since it can use 1-to-1 NAT... But I didn't try it myself yet thought... It's another think I shell try...

**Comment by more1982** [comment]
If it will be usefull, i can give you some logs from my PC, when I'm trying to connect.

**Comment by RSATom** [comment]
Thanks, but I know the reason. So there is no need in your assistance right now.

**Comment by RSATom** [comment]
@more1982 I've pushed changes I hope will help you with your issue. You'll need to do following:
1. [optional] `sudo snap remove rtsp-to-webrtsp` && `sudo snap install rtsp-to-webrtsp --edge` - to update config template to the latest version (or you can just put mentioned below section to your existing `restreamer.conf`)
2. Uncomment [`min-rtp-port` and `rtp-ports-count`](https://github.com/WebRTSP/ReStreamer/blob/master/restreamer.conf.sample#L123-L124) (by removing `#` symbol at the beginning) and put there desired UDP(RTP) interval (more simulations clients you expecting - more wide interval there should be, something like `rtp-ports-count` > = `2 * max clients count`)
3. Uncomment [stun-server](https://github.com/WebRTSP/ReStreamer/blob/dc89f85d76b44fbc6a669ec55586dc8432cb6d1c/restreamer.conf.sample#L121)
4. restart app by `sudo snap restart rtsp-to-webrtsp`

**Comment by RSATom** [comment]
@more1982 any update?

**Comment by more1982** [comment]
> @more1982 any update?

No, It's still not working. Ihave a solution for my problem with media MTX. It is working for me. Thanks

**Comment by RSATom** [comment]
@more1982 so this issue can be closed, right?

**Comment by RSATom** [comment]
Tested the latest version behind router with NAT and following part in `restreamer.conf`:
```
webrtc: {                                                                                                                                                                                                                                                                                                                                         
  min-rtp-port: 5100                                                                                                                                                                                                                                                                                                                              
  rtp-ports-count: 100                                                                                                                                                                                                                                                                                                                            
}   
```
and configured on router forwarding for: TCP 5080, TCP 5554, UDP 5100-5200

and for me it's working...
